-- MySQL Script generated by MySQL Workbench
-- Sat Jan 27 14:49:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `user_id` INT NOT NULL,
  `balance` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entry` (
  `date` DATE NULL,
  `user_user_id` INT NOT NULL,
  `entry_id` INT NOT NULL,
  INDEX `fk_day_user_idx` (`user_user_id` ASC),
  PRIMARY KEY (`entry_id`),
  CONSTRAINT `fk_day_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entry_expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entry_expenses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entry_expenses` (
  `entry_entry_id` INT NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `value` DECIMAL(8,2) NOT NULL,
  `description` VARCHAR(100) NULL,
  `name` VARCHAR(45) NULL,
  CONSTRAINT `fk_entry_expenses_entry1`
    FOREIGN KEY (`entry_entry_id`)
    REFERENCES `mydb`.`entry` (`entry_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entry_earnings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entry_earnings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entry_earnings` (
  `entry_entry_id` INT NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `value` DECIMAL(8,2) NOT NULL,
  `description` VARCHAR(100) NULL,
  `name` VARCHAR(45) NULL,
  CONSTRAINT `fk_entry_earnings_entry1`
    FOREIGN KEY (`entry_entry_id`)
    REFERENCES `mydb`.`entry` (`entry_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
